FROM bde2020/spark-java-template:2.4.0-hadoop2.7


ENV SPARK_APPLICATION_JAR_NAME WordCount-1.0-SNAPSHOT
ENV SPARK_APPLICATION_MAIN_CLASS com.porr.wordcount.Main
ENV SPARK_APPLICATION_ARGS "a b"
ENV ENABLE_INIT_DAEMON=false
